
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label1;

	private global::Gtk.HScale hscale4;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Entry ip;

	private global::Gtk.Button btconnect;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button4;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Button button3;

	private global::Gtk.Button button7;

	private global::Gtk.Button button5;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label BAT;

	private global::Gtk.Entry eBAT;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Label POS;

	private global::Gtk.Entry ePOS;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Label SPL;

	private global::Gtk.Entry eSPL;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Label SPR;

	private global::Gtk.Entry eSPR;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox5;

	private global::Gtk.Label label2;

	private global::Gtk.Label USFL;

	private global::Gtk.VBox vbox6;

	private global::Gtk.Label label3;

	private global::Gtk.Label USFC;

	private global::Gtk.VBox vbox7;

	private global::Gtk.Label label5;

	private global::Gtk.Label USFR;

	private global::Gtk.Image image1;

	private global::Gtk.HBox hbox3;

	private global::Gtk.VBox vbox9;

	private global::Gtk.Label USRL;

	private global::Gtk.Label label4;

	private global::Gtk.VBox vbox11;

	private global::Gtk.Label USRC;

	private global::Gtk.Label label6;

	private global::Gtk.VBox vbox13;

	private global::Gtk.Label USRR;

	private global::Gtk.Label label7;

	private global::Gtk.VBox vbox8;

	private global::Gtk.HBox hbox11;

	private global::Gtk.Label PIT;

	private global::Gtk.Entry ePIT;

	private global::Gtk.HBox hbox13;

	private global::Gtk.Label YAW;

	private global::Gtk.Entry eYAW;

	private global::Gtk.HBox hbox15;

	private global::Gtk.Label ROL;

	private global::Gtk.Entry eROL;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		this.table1.BorderWidth = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Speed");
		this.hbox2.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hscale4 = new global::Gtk.HScale(null);
		this.hscale4.CanFocus = true;
		this.hscale4.Name = "hscale4";
		this.hscale4.Adjustment.Upper = 20D;
		this.hscale4.Adjustment.PageIncrement = 10D;
		this.hscale4.Adjustment.StepIncrement = 1D;
		this.hscale4.Adjustment.Value = 10D;
		this.hscale4.DrawValue = true;
		this.hscale4.Digits = 0;
		this.hscale4.ValuePos = ((global::Gtk.PositionType)(2));
		this.hbox2.Add(this.hscale4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hscale4]));
		w2.Position = 1;
		this.table1.Add(this.hbox2);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox2]));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.ip = new global::Gtk.Entry();
		this.ip.CanFocus = true;
		this.ip.Name = "ip";
		this.ip.Text = global::Mono.Unix.Catalog.GetString("169.254.191.210");
		this.ip.IsEditable = true;
		this.ip.InvisibleChar = '●';
		this.vbox1.Add(this.ip);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.ip]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.btconnect = new global::Gtk.Button();
		this.btconnect.CanFocus = true;
		this.btconnect.Name = "btconnect";
		this.btconnect.UseUnderline = true;
		this.btconnect.Label = global::Mono.Unix.Catalog.GetString("Connect");
		this.vbox1.Add(this.btconnect);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.btconnect]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.table1.Add(this.vbox1);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox1]));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Forward");
		this.vbox2.Add(this.button1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("stop");
		this.vbox2.Add(this.button2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button2]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Backward");
		this.vbox2.Add(this.button4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button4]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Left");
		this.hbox9.Add(this.button3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button3]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button();
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("Stop");
		this.hbox9.Add(this.button7);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button7]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("right");
		this.hbox9.Add(this.button5);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button5]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox2.Add(this.hbox9);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox9]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		this.table1.Add(this.vbox2);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox2]));
		w14.TopAttach = ((uint)(1));
		w14.BottomAttach = ((uint)(2));
		w14.LeftAttach = ((uint)(2));
		w14.RightAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.BAT = new global::Gtk.Label();
		this.BAT.Name = "BAT";
		this.BAT.LabelProp = global::Mono.Unix.Catalog.GetString("BAT");
		this.hbox5.Add(this.BAT);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.BAT]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.eBAT = new global::Gtk.Entry();
		this.eBAT.CanFocus = true;
		this.eBAT.Name = "eBAT";
		this.eBAT.IsEditable = false;
		this.eBAT.InvisibleChar = '●';
		this.hbox5.Add(this.eBAT);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.eBAT]));
		w16.Position = 1;
		this.vbox3.Add(this.hbox5);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.POS = new global::Gtk.Label();
		this.POS.Name = "POS";
		this.POS.LabelProp = global::Mono.Unix.Catalog.GetString("POS");
		this.hbox6.Add(this.POS);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.POS]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.ePOS = new global::Gtk.Entry();
		this.ePOS.CanFocus = true;
		this.ePOS.Name = "ePOS";
		this.ePOS.IsEditable = false;
		this.ePOS.InvisibleChar = '●';
		this.hbox6.Add(this.ePOS);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.ePOS]));
		w19.Position = 1;
		this.vbox3.Add(this.hbox6);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox6]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.SPL = new global::Gtk.Label();
		this.SPL.Name = "SPL";
		this.SPL.LabelProp = global::Mono.Unix.Catalog.GetString("SPL");
		this.hbox7.Add(this.SPL);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.SPL]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.eSPL = new global::Gtk.Entry();
		this.eSPL.CanFocus = true;
		this.eSPL.Name = "eSPL";
		this.eSPL.IsEditable = false;
		this.eSPL.InvisibleChar = '●';
		this.hbox7.Add(this.eSPL);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.eSPL]));
		w22.Position = 1;
		this.vbox3.Add(this.hbox7);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox7]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.SPR = new global::Gtk.Label();
		this.SPR.Name = "SPR";
		this.SPR.LabelProp = global::Mono.Unix.Catalog.GetString("SPR");
		this.hbox8.Add(this.SPR);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.SPR]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.eSPR = new global::Gtk.Entry();
		this.eSPR.CanFocus = true;
		this.eSPR.Name = "eSPR";
		this.eSPR.IsEditable = false;
		this.eSPR.InvisibleChar = '●';
		this.hbox8.Add(this.eSPR);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.eSPR]));
		w25.Position = 1;
		this.vbox3.Add(this.hbox8);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox8]));
		w26.Position = 3;
		w26.Expand = false;
		w26.Fill = false;
		this.table1.Add(this.vbox3);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox3]));
		w27.TopAttach = ((uint)(1));
		w27.BottomAttach = ((uint)(2));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("US FL");
		this.vbox5.Add(this.label2);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label2]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.USFL = new global::Gtk.Label();
		this.USFL.Name = "USFL";
		this.USFL.LabelProp = global::Mono.Unix.Catalog.GetString("0");
		this.vbox5.Add(this.USFL);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.USFL]));
		w29.Position = 1;
		w29.Expand = false;
		w29.Fill = false;
		this.hbox1.Add(this.vbox5);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox5]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("US FC");
		this.vbox6.Add(this.label3);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label3]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.USFC = new global::Gtk.Label();
		this.USFC.Name = "USFC";
		this.USFC.LabelProp = global::Mono.Unix.Catalog.GetString("0");
		this.vbox6.Add(this.USFC);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.USFC]));
		w32.Position = 1;
		w32.Expand = false;
		w32.Fill = false;
		this.hbox1.Add(this.vbox6);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox6]));
		w33.Position = 1;
		w33.Expand = false;
		w33.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("US FR");
		this.vbox7.Add(this.label5);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label5]));
		w34.Position = 0;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.USFR = new global::Gtk.Label();
		this.USFR.Name = "USFR";
		this.USFR.LabelProp = global::Mono.Unix.Catalog.GetString("0");
		this.vbox7.Add(this.USFR);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.USFR]));
		w35.Position = 1;
		w35.Expand = false;
		w35.Fill = false;
		this.hbox1.Add(this.vbox7);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox7]));
		w36.Position = 2;
		w36.Expand = false;
		w36.Fill = false;
		this.vbox4.Add(this.hbox1);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image();
		this.image1.Name = "image1";
		this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("TestUI.voiture.png");
		this.vbox4.Add(this.image1);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.image1]));
		w38.Position = 1;
		w38.Expand = false;
		w38.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.USRL = new global::Gtk.Label();
		this.USRL.Name = "USRL";
		this.USRL.LabelProp = global::Mono.Unix.Catalog.GetString("0");
		this.vbox9.Add(this.USRL);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.USRL]));
		w39.Position = 0;
		w39.Expand = false;
		w39.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("US RL");
		this.vbox9.Add(this.label4);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label4]));
		w40.Position = 1;
		w40.Expand = false;
		w40.Fill = false;
		this.hbox3.Add(this.vbox9);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox9]));
		w41.Position = 0;
		w41.Expand = false;
		w41.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.USRC = new global::Gtk.Label();
		this.USRC.Name = "USRC";
		this.USRC.LabelProp = global::Mono.Unix.Catalog.GetString("0");
		this.vbox11.Add(this.USRC);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.USRC]));
		w42.Position = 0;
		w42.Expand = false;
		w42.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("US RC");
		this.vbox11.Add(this.label6);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.label6]));
		w43.Position = 1;
		w43.Expand = false;
		w43.Fill = false;
		this.hbox3.Add(this.vbox11);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox11]));
		w44.Position = 1;
		w44.Expand = false;
		w44.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox13 = new global::Gtk.VBox();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.USRR = new global::Gtk.Label();
		this.USRR.Name = "USRR";
		this.USRR.LabelProp = global::Mono.Unix.Catalog.GetString("0");
		this.vbox13.Add(this.USRR);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.USRR]));
		w45.Position = 0;
		w45.Expand = false;
		w45.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("US RR");
		this.vbox13.Add(this.label7);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.label7]));
		w46.Position = 1;
		w46.Expand = false;
		w46.Fill = false;
		this.hbox3.Add(this.vbox13);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox13]));
		w47.Position = 2;
		w47.Expand = false;
		w47.Fill = false;
		this.vbox4.Add(this.hbox3);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox3]));
		w48.Position = 2;
		w48.Expand = false;
		w48.Fill = false;
		this.table1.Add(this.vbox4);
		global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox4]));
		w49.TopAttach = ((uint)(1));
		w49.BottomAttach = ((uint)(2));
		w49.LeftAttach = ((uint)(1));
		w49.RightAttach = ((uint)(2));
		w49.XOptions = ((global::Gtk.AttachOptions)(4));
		w49.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.PIT = new global::Gtk.Label();
		this.PIT.Name = "PIT";
		this.PIT.LabelProp = global::Mono.Unix.Catalog.GetString("PIT");
		this.hbox11.Add(this.PIT);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.PIT]));
		w50.Position = 0;
		w50.Expand = false;
		w50.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.ePIT = new global::Gtk.Entry();
		this.ePIT.CanFocus = true;
		this.ePIT.Name = "ePIT";
		this.ePIT.IsEditable = true;
		this.ePIT.InvisibleChar = '●';
		this.hbox11.Add(this.ePIT);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.ePIT]));
		w51.Position = 1;
		this.vbox8.Add(this.hbox11);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox11]));
		w52.Position = 0;
		w52.Expand = false;
		w52.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.YAW = new global::Gtk.Label();
		this.YAW.Name = "YAW";
		this.YAW.LabelProp = global::Mono.Unix.Catalog.GetString("YAW");
		this.hbox13.Add(this.YAW);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.YAW]));
		w53.Position = 0;
		w53.Expand = false;
		w53.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.eYAW = new global::Gtk.Entry();
		this.eYAW.CanFocus = true;
		this.eYAW.Name = "eYAW";
		this.eYAW.IsEditable = true;
		this.eYAW.InvisibleChar = '●';
		this.hbox13.Add(this.eYAW);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.eYAW]));
		w54.Position = 1;
		this.vbox8.Add(this.hbox13);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox13]));
		w55.Position = 1;
		w55.Expand = false;
		w55.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.ROL = new global::Gtk.Label();
		this.ROL.Name = "ROL";
		this.ROL.LabelProp = global::Mono.Unix.Catalog.GetString("ROL");
		this.hbox15.Add(this.ROL);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.ROL]));
		w56.Position = 0;
		w56.Expand = false;
		w56.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.eROL = new global::Gtk.Entry();
		this.eROL.CanFocus = true;
		this.eROL.Name = "eROL";
		this.eROL.IsEditable = true;
		this.eROL.InvisibleChar = '●';
		this.hbox15.Add(this.eROL);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.eROL]));
		w57.Position = 1;
		this.vbox8.Add(this.hbox15);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox15]));
		w58.Position = 2;
		w58.Expand = false;
		w58.Fill = false;
		this.table1.Add(this.vbox8);
		global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox8]));
		w59.TopAttach = ((uint)(2));
		w59.BottomAttach = ((uint)(3));
		w59.XOptions = ((global::Gtk.AttachOptions)(4));
		w59.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add(this.table1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 804;
		this.DefaultHeight = 1088;
		this.Show();
		this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
		this.button2.Clicked += new global::System.EventHandler(this.OnButton2Clicked);
		this.button4.Clicked += new global::System.EventHandler(this.OnButton4Clicked);
		this.button3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
		this.button7.Clicked += new global::System.EventHandler(this.OnButton7Clicked);
		this.button5.Clicked += new global::System.EventHandler(this.OnButton5Clicked);
		this.btconnect.Clicked += new global::System.EventHandler(this.OnBtconnectClicked);
		this.hscale4.ValueChanged += new global::System.EventHandler(this.OnHscale4ValueChanged);
	}
}
