
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label1;

	private global::Gtk.HScale hscale4;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button button3;

	private global::Gtk.Button button7;

	private global::Gtk.Button button5;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Entry ip;

	private global::Gtk.Button btconnect;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button4;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label label2;

	private global::Gtk.Entry USFL;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Label label3;

	private global::Gtk.Entry USFC;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Label label5;

	private global::Gtk.Entry USFR;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		this.table1.BorderWidth = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Speed");
		this.hbox2.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hscale4 = new global::Gtk.HScale(null);
		this.hscale4.CanFocus = true;
		this.hscale4.Name = "hscale4";
		this.hscale4.Adjustment.Upper = 20D;
		this.hscale4.Adjustment.PageIncrement = 10D;
		this.hscale4.Adjustment.StepIncrement = 1D;
		this.hscale4.Adjustment.Value = 10D;
		this.hscale4.DrawValue = true;
		this.hscale4.Digits = 0;
		this.hscale4.ValuePos = ((global::Gtk.PositionType)(2));
		this.hbox2.Add(this.hscale4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hscale4]));
		w2.Position = 1;
		this.table1.Add(this.hbox2);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox2]));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Left");
		this.hbox4.Add(this.button3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button3]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button();
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("Stop");
		this.hbox4.Add(this.button7);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button7]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("right");
		this.hbox4.Add(this.button5);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button5]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.table1.Add(this.hbox4);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox4]));
		w7.TopAttach = ((uint)(2));
		w7.BottomAttach = ((uint)(3));
		w7.LeftAttach = ((uint)(2));
		w7.RightAttach = ((uint)(3));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.ip = new global::Gtk.Entry();
		this.ip.CanFocus = true;
		this.ip.Name = "ip";
		this.ip.Text = global::Mono.Unix.Catalog.GetString("169.254.191.210");
		this.ip.IsEditable = true;
		this.ip.InvisibleChar = '●';
		this.vbox1.Add(this.ip);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.ip]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.btconnect = new global::Gtk.Button();
		this.btconnect.CanFocus = true;
		this.btconnect.Name = "btconnect";
		this.btconnect.UseUnderline = true;
		this.btconnect.Label = global::Mono.Unix.Catalog.GetString("Connect");
		this.vbox1.Add(this.btconnect);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.btconnect]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.table1.Add(this.vbox1);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox1]));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Forward");
		this.vbox2.Add(this.button1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("stop");
		this.vbox2.Add(this.button2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button2]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Backward");
		this.vbox2.Add(this.button4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button4]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.table1.Add(this.vbox2);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox2]));
		w14.TopAttach = ((uint)(1));
		w14.BottomAttach = ((uint)(2));
		w14.LeftAttach = ((uint)(2));
		w14.RightAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("US FL");
		this.hbox5.Add(this.label2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label2]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.USFL = new global::Gtk.Entry();
		this.USFL.CanFocus = true;
		this.USFL.Name = "USFL";
		this.USFL.IsEditable = false;
		this.USFL.InvisibleChar = '●';
		this.hbox5.Add(this.USFL);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.USFL]));
		w16.Position = 1;
		this.vbox3.Add(this.hbox5);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("US FC");
		this.hbox7.Add(this.label3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label3]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.USFC = new global::Gtk.Entry();
		this.USFC.CanFocus = true;
		this.USFC.Name = "USFC";
		this.USFC.IsEditable = false;
		this.USFC.InvisibleChar = '●';
		this.hbox7.Add(this.USFC);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.USFC]));
		w19.Position = 1;
		this.vbox3.Add(this.hbox7);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox7]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("US FR");
		this.hbox9.Add(this.label5);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label5]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.USFR = new global::Gtk.Entry();
		this.USFR.CanFocus = true;
		this.USFR.Name = "USFR";
		this.USFR.IsEditable = false;
		this.USFR.InvisibleChar = '●';
		this.hbox9.Add(this.USFR);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.USFR]));
		w22.Position = 1;
		this.vbox3.Add(this.hbox9);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox9]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		this.table1.Add(this.vbox3);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox3]));
		w24.LeftAttach = ((uint)(1));
		w24.RightAttach = ((uint)(2));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add(this.table1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 499;
		this.DefaultHeight = 300;
		this.Show();
		this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
		this.button2.Clicked += new global::System.EventHandler(this.OnButton2Clicked);
		this.button4.Clicked += new global::System.EventHandler(this.OnButton4Clicked);
		this.btconnect.Clicked += new global::System.EventHandler(this.OnBtconnectClicked);
		this.button3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
		this.button7.Clicked += new global::System.EventHandler(this.OnButton7Clicked);
		this.button5.Clicked += new global::System.EventHandler(this.OnButton5Clicked);
		this.hscale4.ValueChanged += new global::System.EventHandler(this.OnHscale4ValueChanged);
	}
}
